version: '3.8'

services:
  postgres:
    image: postgis/postgis:15-3.4
    container_name: floatchat_db
    environment:
      POSTGRES_DB: floatchat_db
      POSTGRES_USER: floatchat_user
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U floatchat_user -d floatchat_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - floatchat_network

  redis:
    image: redis:7-alpine
    container_name: floatchat_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - floatchat_network

volumes:
  postgres_data:
  redis_data:

networks:
  floatchat_network:
    driver: bridge